yahoo/fetchr

- README.md
> [skip-ci] Update README with API section

- libs/util/http.client.js
> only add content-type header for PUT and POST requests

- libs/fetcher.js
- tests/unit/libs/fetcher.js
Hey !
This PR gives more insight of what fetcher you're trying to get.
> A more helpful error message for getFetcher

- libs/fetcher.client.js
- libs/fetcher.js
- package.json
- tests/mock/MockErrorService.js
- tests/mock/MockService.js
- tests/mock/app.js
- tests/unit/libs/fetcher.client.js
- tests/unit/libs/fetcher.js
Also, use supertest for better coverage.
@mridgway @redonkulus
> Use JSON.parse on query string values in case they are arrays or objects

- libs/fetcher.client.js
- libs/fetcher.js
- tests/unit/libs/fetcher.js
Remove "/resource" prefix in url.
see #65  for more details
> Remove path prefix '/resource' for endpoint url

- README.md
- libs/fetcher.client.js
- libs/util/http.client.js
- package.json
- tests/mock/corsApp.js
- tests/unit/libs/fetcher.client.js
> allow override of constructGetUri along w/ potential CORS support

- README.md
- libs/fetcher.client.js
- libs/util/http.client.js
- package.json
- tests/mock/corsApp.js
- tests/unit/libs/fetcher.client.js
> backport CORS support for v0.4

- libs/util/http.client.js
> add in #76 PR to 0.4 branch

- libs/fetcher.js
added headers for non-get errors too. >.< missed this just now!
> add headers for non-get errors too

- libs/fetcher.client.js
- libs/util/defaultConstructGetUri.js
> move default constructGetUri function to its own file

- libs/util/http.client.js
@redonkulus 
1. different error message from https://github.com/Raynos/xhr/blob/master/index.js#L77
1. more information from `xhr` module https://github.com/Raynos/xhr/blob/master/index.js#L38-L44
> Adding more debug information for error

- README.md
- libs/fetcher.client.js
- libs/fetcher.js
- libs/util/http.client.js
In response to: #87 
- Update fetcher.client config name to clientConfig
- Add docs to reflect difference between client and server side config objects.
> Fetcher.client config object name

- libs/util/http.client.js
> cherry-pick lodash methods for smaller build

- libs/fetcher.js
- package.json
- tests/unit/libs/fetcher.js
I also fixed some old tests in this PR.
@redonkulus @lingyan @geekyme
> [Fixes #81] Don't throw on invalid fetcher access

- libs/fetcher.js
- tests/unit/libs/fetcher.js
> [Fixes #101] isRegistered handles sub resources

- libs/fetcher.client.js
- libs/fetcher.js
- tests/unit/libs/fetcher.js
> Improve test coverage

- README.md
- libs/fetcher.client.js
- libs/util/http.client.js
- tests/unit/libs/fetcher.client.js
- tests/unit/libs/util/http.client.js
> Allow setting of xhr timeout for all request

- README.md
> Add error handling doc

- libs/fetcher.js
- tests/unit/libs/fetcher.js
> [Fix #119] Don't cast big integers to numbers, leave as strings.

- libs/fetcher.client.js
- libs/fetcher.js
- package.json
- tests/unit/libs/fetcher.client.js
- tests/unit/libs/fetcher.js
@redonkulus @mridgway 
TODO: Client side promise support
> [#111] Add promise support

- README.md
- docs/fetchr.md
- libs/fetcher.client.js
- libs/fetcher.js
- tests/mock/MockService.js
- tests/mock/app.js
- tests/unit/libs/fetcher.client.js
- tests/unit/libs/fetcher.js
@redonkulus @mridgway 
Move logic from `fluxible-plugin-fetchr` into here and refactor. https://github.com/yahoo/fluxible-plugin-fetchr/pull/48
> Refactor service metadata

- libs/fetcher.js
@Vijar seems like there's an extra `excuteRequest`
> remove extra executeRequest

- README.md
The phrasing "contains valid JSON" sounded to me like this should be a JSON string.
> Clarify type of output property in README

- README.md
- libs/fetcher.client.js
- libs/util/defaultConstructGetUri.js
- libs/util/http.client.js
- package.json
- tests/unit/libs/fetcher.client.js
Trying to help out. Upgraded to lodash 4.0.1, small adjustment made to contextPicker, added tests, updated readme. For history see issue #137 . The TLDR; is contextPicker no longer accepts an object as the third arg.
> lodash 4.0.1 upgrade

- README.md
- libs/fetcher.client.js
- libs/fetcher.js
- tests/unit/libs/fetcher.client.js
- tests/unit/libs/fetcher.js
- tests/util/defaultOptions.js
- tests/util/testCrud.js
This allows apps to provide their custom function to collect stats for fetchr requests.
@yahoo/team-fluxible
> support fetchr stats collection and monitoring

- libs/fetcher.js
- tests/unit/libs/fetcher.js
> Check whether the number is valid in params in order to avoid Infinity

- README.md
- libs/fetcher.client.js
- tests/unit/libs/fetcher.client.js
This PR is alternative for #155.
I closed #155 because of dirty commit log.
> Add custom request header

- libs/fetcher.client.js
- libs/fetcher.js
- package-lock.json
- package.json
Add setImmediate polyfill﻿
Fixes #195
> Add setImmediate polyfill

- libs/fetcher.js
- tests/unit/libs/fetcher.js
> fetcher: improve error messages

- .github/workflows/node.js.yml
- README.md
> ci: add github actions

- .eslintrc.js
- .github/dependabot.yml
- .github/workflows/node.js.yml
- .prettierignore
- CONTRIBUTING.md
- LICENSE.md
- README.md
- docs/fetchr.md
- examples/simple/package.json
- examples/simple/shared/index.html
- package-lock.json
- package.json
> refactor: use prettier directly

- .eslintrc.js
- libs/fetcher.client.js
- libs/fetcher.js
- package-lock.json
- package.json
> Remove es6 promise

- libs/fetcher.client.js
- package-lock.json
- package.json
- tests/unit/libs/fetcher.client.js
- tests/util/testCrud.js
> refactor: remove deepmerge as dependency

- libs/fetcher.client.js
This feature was removed by mistake in #343.
> fix: add back config support for READ operation with POST request

- libs/fetcher.js
While it's nice to let people know about deprecations, we also have changelogs and semver. This PR reduces log spam for people who either can't or won't update `.name` to `.resource` currently, but will address it if/when updating semver ranges.
> chore: remove unnecessary warning
