yahoo/fetchr

- libs/fetcher.client.js
@redonkulus 
resolves #59 
see [methods, methods, methods in the lodash release](https://github.com/lodash/lodash/releases/tag/3.0.0)
> cherry-pick lodash methods.

- libs/fetcher.js
- tests/unit/libs/fetcher.js
@Vijar @mridgway 
It's common for data fetchers to want to set custom response headers, especially headers like cache-control for GET requests.
> support custom response headers

- libs/util/http.client.js
We do not pass response in the event of errors but often APIs provide lots of good details in an error response, such as error codes that we can use to notify the user about. This change attaches body of api response to the err object.
> Pass response body for errors

- libs/fetcher.js
This provides the use case for error responses that contain some special headers to be sent to the client.
> set headers for both errors and success

- libs/fetcher.js
- tests/unit/libs/fetcher.js
@lingyan 
This is so we're consistent in sending the same format response from the middleware.
> Return json for error response

- libs/util/http.client.js
- tests/unit/libs/util/http.client.js
@Vijar 
* add X-Requested-With header (addresses https://github.com/yahoo/fetchr/issues/83)
* fix a bug that broke retry, discovered while adding unit test for http.client.js
* had to turn off retry by default to keep backward compatibility
> add X-Requested-With header; bug fix

- libs/fetcher.client.js
- libs/util/defaultConstructGetUri.js
- libs/util/http.client.js
- tests/unit/libs/util/http.client.js
@Vijar @redonkulus  Back port https://github.com/yahoo/fetchr/pull/84 and https://github.com/yahoo/fetchr/pull/85
> Backport PR #84 and #85

- libs/fetcher.js
For requests other than "GET" requests, add a fallback config object so config is never undefined when service is called.
Is response to: #94
> Add fallback config object

- libs/util/http.client.js
- tests/unit/libs/util/http.client.js
This should hopefully fix #90. I've tried to incorporate appropriate tests based on scenarios that I've seen before the commit created the problem, as well as scenarios I saw from an IIS server housing node where it stripped out the body content.
> handle error 400 json responses and standard string responses

- libs/util/http.client.js
- tests/unit/libs/util/http.client.js
This PR prevents the `X-Requested-With` header from being set when making CORS requests, since that header causes an undesired preflight OPTIONS request. See #83 for original mention.
> Remove X-Requested-With header when performing CORS requests

- README.md
- examples/simple/server/fetchers/flickr.js
- examples/simple/shared/getFlickrPhotos.js
- libs/fetcher.client.js
- libs/fetcher.js
- tests/unit/libs/fetcher.client.js
- tests/unit/libs/fetcher.js
@redonkulus @mridgway @lingyan 
Sorry this is so huge, one thing led to another down the rabbit hole. This PR includes:
- New interface for CRUD methods w/ backwards compatibility
- Deprecated old interface
- Renamed all instances of 'fetchers' to 'services' w/ backwards compatibility
- Deprecated `registerFetcher` and `getFetcher`
- Fixed an issue where custom `constructGetUri` function wasn't falling back properly
- Housekeeping on test suite
- Deleted old batching code
> [Fixes #108] Refactor CRUD interface

- docs/fetchr.md
- libs/fetcher.client.js
- libs/fetcher.js
- package.json
- tests/unit/libs/fetcher.client.js
- tests/unit/libs/fetcher.js
@Vijar @redonkulus, 
1. this PR provides users opportunity to update options, e.g., if they want to set different `xhrTimeout`.
> provide function to update options

- libs/fetcher.js
- tests/mock/MockErrorService.js
- tests/unit/libs/fetcher.js
As I suggested in https://github.com/yahoo/fetchr/issues/97#issuecomment-127982042
Possibility to return more data in errors, by supplying a method called `.toSafeJSON()` on the error object itself.
Thoughts? Suggestions on another name for the method?
> Chatty errors

- README.md
- docs/fetchr.md
- libs/fetcher.client.js
- tests/unit/libs/fetcher.client.js
@Vijar @redonkulus @mridgway @lingyan 
Add a new option `contextPicker`, so that users can define how to pick the context values, for example they can ignore certain key for certain method.
the pick function is exactly the predicate function of `lodash/object/pick`, 
```js
var fetcher = new Fetcher({
context: { // These context values are persisted with XHR calls as query params
_csrf: 'Ax89D94j',
device: 'desktop'
},
contextPicker: {
GET: function (value, key, object) {
// for example, if you don't enable CSRF protection for GET, you are able to ignore it with the url
if (key === '_csrf') {
return false;
}
rerurn true;
}
// for other method e.g., POST, if you don't define the picker, it will pick the entire context object
}
});
```
> add context picker support

- libs/fetcher.client.js
- libs/fetcher.js
@Vijar @mridgway 
bluebird prints "Unhandled rejection" error when the promise is rejected without a rejected handler: https://github.com/petkaantonov/bluebird/blob/master/src/captured_trace.js#L267
fetchr.js currently uses `global.Promise`, which could be set by app to bluebird.  So to suppress this bluebird error, we need to register a no-op rejected handler.
Alternative is to simply use es6-promise in fetchr, instead of global.Promise and fallback to es6-promise.
> chain promise to avoid bluebird's "Unhandled rejection" error

- libs/util/defaultConstructGetUri.js
- tests/unit/libs/fetcher.client.js
fixes #55 
Params that are `undefined` are being passed in the uri and then returned as the string `"undefined"`. It seems more appropriate to avoid sending any params that are `undefined`.
> avoid sending undefined params in the uri

- README.md
- libs/fetcher.js
- tests/unit/libs/fetcher.js
@mridgway @Vijar @lingyan 
This allows applications the ability to add additional information to the XHR response before it is sent to the client. A typical use case might be to add debug information or performance metrics for XHR requests.
> Add responseFormatter support

- libs/fetcher.js
- tests/mock/MockErrorService.js
- tests/unit/libs/fetcher.js
Up till version 0.5.17 erroneous responses were able to carry meta-data. Is it possible to reinstate this capability in new versions of fetchr? Or is there a reason for disallowing meta-data from being passed on when the service fails? Thanks!
> Allow setting of headers for erroneous responses

- .npmignore
- libs/fetcher.js
- tests/unit/libs/fetcher.js
@Vijar @redonkulus 
* escape resource name in error output
Based on [this owasp guideline](https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet#RULE_.233.1_-_HTML_escape_JSON_values_in_an_HTML_context_and_read_the_data_with_JSON.parse), 
```
Ensure returned Content-Type header is application/json and not text/html.
This shall instruct the browser not misunderstand the context and execute injected script.
```
Escaping is not needed for JSON data output, as long as the content-type header is set correctly to `Content-Type: application/json; charset=utf-8`, which fetchr already does with `res.json()`.
But there could be legacy browsers with security bugs that do not respect this, such as Opera browser prior to Opera 11.65  (Latest Opera is at 34.0 as of now.): …
> Security related fixes

- README.md
- libs/fetcher.js
- tests/unit/libs/fetcher.js
400 is for client error.  Propose to use 500 instead.  Theoretically, this is a breaking change.  We can make it a non breaking change, by allowing people to configure default error code to return.  But don't think it is worth the trouble.  We can go 1.0 with this :)
@Vijar @mridgway @redonkulus
> use 500 as default status code for errors, instead of 400

- README.md
- libs/fetcher.client.js
- libs/util/http.client.js
- tests/unit/libs/fetcher.client.js
@redonkulus @mridgway @praveenbnsm
We actually can expose the xhr object with little effort, but it just won't work with our promise interface though.
Fixes #142
> Expose xhr object for aborts

- libs/fetcher.client.js
- tests/util/testCrud.js
if the Promise's catch handler returns just a value, the Promise becomes fulfilled. So, it should return a rejected Promises.
> Returning rejected Promise when error occurred

- libs/fetcher.js
- package.json
- tests/util/testCrud.js
In a server-side fetcher, there is currently no way to handle any error that's thrown by `Fetcher.getService` (since it gets executed via `setImmediate` inside of a promise constructor).
In particular, if you specify an invalid resource name (and that's easy to do for the new people on team in a substantially complex app), an error ends up in `uncaughtException` handler (or crashes the server).
> Invalid resource error handling

- libs/fetcher.client.js
`result` is parsed by [`parseResponse()`](https://github.com/yahoo/fetchr/compare/defensive?expand=1#diff-84c4f8c88b61ef0647afbcf02f0ae99cR30), which could return `null`
> be defensive. result could be null

- libs/fetcher.js
- tests/mock/MockNoopService.js
- tests/mock/mockApp.js
- tests/mock/mockCorsApp.js
- tests/unit/libs/fetcher.js
- tests/util/testCrud.js
`service[op].apply(service, args)` throws exception when `service[op]` is undefined.
And this task is called under `setImmediate`, so if service does not have the specified operation, `process.on('uncaughtException')` will be thrown. 
This PR is to avoid the above situation.
> check service operation is defined

- libs/fetcher.js
- tests/unit/libs/fetcher.js
I think fetcher.js should allow only 'read,create,update,delete' operations that fetchr.client supports.
because I could call any operation like 'constructor'. this may cause serious security problem.
```
curl -X POST http://localhost:3000/proxy -H "Content-Type:application/json" -d '{ "context":{},"requests":{ "g0": {"resource": "bookmarking", "operation": "constructor", "params":{}}}}' 
```
> prevent unsupported operation call

- libs/util/http.client.js
- tests/unit/libs/util/http.client.js
As figured out in #175 `err.timeout` was only set when there was a `408` response but not when the `xhr` callback receives a timeout error.
> Always set timeout property for error object

- README.md
- docs/fetchr.md
- examples/simple/server/fetchers/flickr.js
- libs/fetcher.js
- tests/mock/MockErrorService.js
- tests/mock/MockNoopService.js
- tests/mock/MockService.js
- tests/unit/libs/fetcher.js
- tests/util/defaultOptions.js
- tests/util/testCrud.js
> fetcher: rename service.name to service.resource

- libs/fetcher.client.js
- libs/util/defaultConstructGetUri.js
- libs/util/forEach.js
- libs/util/http.client.js
- package-lock.json
- package.json
> Remove lodash from dependencies

- libs/fetcher.client.js
The problem was on the following code:
```
return { [p]: context[p] };
```
ie11 doesn't support this shortcut and sees it as syntax error. I wan the script on ie11 on win7 and I don't get any syntax error anymore.
Solves #251 
> fix ie11 regression on fetcher.client.js

- README.md
- libs/util/http.client.js
- tests/unit/libs/util/http.client.js
@redonkulus while thinking in a way of adding retry mechanism to fetchr to solve an issue in my company, I discovered that fetchr already has support for it. I went deeper on it and realized that there was a bug with the retry interval and that the status code check was only supporting 408 and xhr failures. Then I fixed the bug and add support for custom status while keeping it backward compatible.
- fix initial retry.interval not being respected
- add support for custom response status codes to be retried automatically
**UPDATE:**
- add full jitter formula for interval calculation
- deprecate `max_retries` in favor of `maxRetries` 
- add documentation
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and …
> Improve retry mechanism

- libs/util/http.client.js
@redonkulus `String.prototype.trim` was added in IE9. IE8 was deprecated by MS [in 2016](https://www.microsoft.com/en-us/microsoft-365/windows/end-of-ie-support). IMO we could remove this polyfill without a need of a major release since people only need support for IE11 (but I might be wrong). What do you think?
> http: remove trim polyfill

- libs/fetcher.client.js
- libs/fetcher.js
- package-lock.json
- package.json
In the server part, I just removed the import since node already has setImmediate since version 0.9.1.
In the client part, I completely remove it in the promise branch and replaced it with setTimeout in the client branch.
> Remove setImmediate polyfill

- libs/fetcher.js
- package-lock.json
- package.json
We were only using object-assign on server so we can safely replace it
with the native implementation.
> package.json: remove unnecessary object-assign dependency

- libs/util/http.client.js
- tests/unit/libs/util/http.client.js
@redonkulus while refactoring the tests for the other PR, I realized that we don't use `delete` nor `put` from the http module.
> http: remove unused put and delete methods

- .eslintrc.js
- README.md
- docs/fetchr.md
- libs/fetcher.client.js
- libs/util/defaultConstructGetUri.js
- libs/util/http.client.js
- package-lock.json
- package.json
- tests/functional/fetchr.test.js
- tests/functional/server.js
- tests/mock/mockApp.js
- tests/unit/libs/fetcher.client.js
- tests/unit/libs/util/http.client.js
- tests/unit/setup.js
- Completely replaced xhr with fetch
- Removed all xhr names from the docs
- Added note for users that they need to install a polyfill if they need to support old browsers
- The current API is still backward compatible
- Remove xhr names from the public API (eg. xhrPath, xhrTimeout). I didn't do it right now since it would require users to update their code in order to benefit from this update;
- Fix the retry/abort bug that I mentioned on #278. I fixed it in a local branch but with xhr. Then I realized that I would have to rewrite everything again to make it work with fetch. So I opted to keep the bug for now;
- I didn't cleanup much the code. I tried to keep everything as it was as much as possible. While it was very tempting to refactor everything, I think the PR would get huge and …
> Replace xhr with native fetch

- libs/fetcher.client.js
- libs/fetcher.js
- tests/functional/fetchr.test.js
- tests/functional/resources/error.js
- tests/mock/MockErrorService.js
- tests/mock/MockService.js
- tests/unit/libs/fetcher.client.js
- tests/unit/libs/fetcher.js
`returnMeta` query param was introduced in order to handle a response format update from the server. There was a time that we would return the data from the resources without making any change. When `returnMeta` was introduced, we started formatting the response as following:
```js
// successful responses:
{
data: serviceResponseData,
meta: serviceResponseMeta,
}
// error responses:
{
output: serviceErrorOutput,
meta: serviceResponseMeta,
}
```
`returnMeta` was then added to prevent outdated clients to break because of the new format. Years have passed and all browsers should have a fresh copy of fetchr by now. Therefore, we can remove the support for it as requested in the TODO comments (ex. https://github.com/yahoo/fetchr/blob/241a71c204b17f25f7c5ff403e054ab70782425d/libs/fetcher.client. …
> Remove support for returnMeta query param

- libs/util/http.client.js
GET requests do not have a content, so no content-type header needed.
POST requests, in theory, could have any content-type since users could use any kind of express middleware that would populate req.body. The only use case that I see is to upload pictures. One could use a multipart form data to do that. But this person would need to know fetchr middleware implementation in order to make it work properly. But I bet that we all know better options to upload media that would be easier than to hack fetchr. 
So, IMO, it doesn't make sense to provide this feature. Am I missing something? 
What I'm trying to do now is to make the requests/responses as consistent as possible so we can simplify the code. I'm mainly concerned about error handling, this is where the code here is the ugliest IMO. …
> client: remove support for custom request Content-type

- libs/fetcher.client.js
- tests/functional/fetchr.test.js
- tests/unit/libs/fetcher.client.js
Currently, we only add the resource name in the path for GET requests:
`fetchr.read('resource-name')` => `/api/resource-name`.
But we never do it for POST requests:
`fetchr.read('resource-name').params(hugePayload)` => `/api`.
This behavior makes it hard to build monitoring tools on top of it. For example, one could have a gateway in front of `fetchr` that monitors the response success rate per path and triggers an alert if the rate drops. For GET requests, it is easy to spot which resource is the faulty one, but for POST requests it's just impossible without diving into the logs of the service where fetchr is running. It's definitely doable, but not easy if the team that manages the gateway have no idea what is behind it.
Another challenge would be to add a circuit breaker per resource. …
> feat: add resource name in POST path requests

- index.js
- libs/fetcher.js
- package.json
This changes should even work with the already unsupported Node 10 (the functional tests pass, but unit don't since we already use some modern APIs there).
> refactor: use modern javascript in the server code

- libs/fetcher.client.js
- libs/fetcher.js
- libs/util/http.client.js
- libs/util/pickContext.js
- tests/unit/libs/fetcher.js
- tests/unit/libs/util/http.client.js
Support for batched requests was drop a long time ago (see: https://github.com/yahoo/fetchr/pull/110) but we still have some code from that time.
By removing it completely, GET and POST requests are almost identical (the only difference is that POST has a body). This allows us to do some refactoring to remove many code duplication.
The change is quite big (and is on top of #342, so I recommend to merge that one first) but hopefully, reviewing commit by commit should make it easier to review.
> refactor: remove unused batching code and remove duplication

- libs/fetcher.client.js
- libs/util/http.client.js
- tests/unit/libs/fetcher.client.js
- tests/unit/libs/util/http.client.js
Summary of changes:
- replace `get` and `post` with only one method:`httpRequest`
- `httpRequest` always returns a promise (fetcher is now the only responsible for handling the callback flow)
- Simplify http request options normalization
Again, I recommend you to review commit by commit ;)
> refactor(http): remove callbacks, simplify options normalization and export only one function

- libs/fetcher.client.js
- libs/util/defaultConstructGetUri.js
- libs/util/http.client.js
- libs/util/httpRequest.js
- libs/util/normalizeOptions.js
- libs/util/url.js
- tests/unit/libs/fetcher.client.js
- tests/unit/libs/util/http.client.js
- tests/unit/libs/util/httpRequest.js
This is the last big refactoring one. Here, I'm merging the code related to options normalization from the `http.client` and `fetchr.cleint` modules. As you can see, when you put both together, we have a bunch of code (that I'll probably simplify in another PR).
By centralizing the options we basically create only one interface that is passed down to all functions (it will be helpful when migrating to ts). 
But more importantly, `httpRequest` does not compute the options unnecessarily on every retry. This makes the plate clean to fix the corner cases that I mentioned in the other PR:
- do not retry user requests aborted by the user
- add abort support for the promise flow
There will be also another PR improving the `FetchrError` class:
- Make it inherit from `Error`;
- Attach the …
> refactor: join options logic from http and fetchr client modules

- README.md
- libs/fetcher.js
- libs/util/httpRequest.js
- tests/functional/fetchr.test.js
- tests/util/testCrud.js
After migrating from xhr to native fetch, many cases inside `FetchrError` were not reachable anymore. I didn't refactor it back that time since the code was super hard to understand and we didn't have functional tests to see the real consequences of updating it. But now it was a breeze.
Hopefully, FetchrError class is easier to understand now. I also briefly document it in the README and, as you can see, the data inside the error could be better and simplified. But it would introduce some breaking changes that I would postpone for V1 now.
> refactor: simplify FetchrError and fix Error inheritance

- libs/util/httpRequest.js
- tests/functional/app.js
- tests/functional/fetchr.test.js
- tests/functional/resources/alwaysSlow.js
- tests/functional/resources/slowThenFast.js
If we don't create a new AbortController on every retry, the abort
method will have a reference to the first controller that is already
expired.
We must also pay attention to not use the same controller on every
request, otherwise retries would not be possible.
> fix: allow requests to be aborted after retries and timeouts

- README.md
- libs/fetcher.client.js
- libs/util/normalizeOptions.js
- tests/unit/libs/fetcher.client.js
@redonkulus we were only able to set retry configuration per request. Now, it's possible to set some (or all) configuration globally:
```js
const fetchr = new Fetchr({
retry: {
interval: 350,
statusCodes: [0, 502, 504],
},
});
fetchr.read('resource').clientConfig({ retry: { maxRetries: 2 } }).end();
```
This avoids repeating some configuration that (at least in our case) are always the same.
> feat(client): add support for global retry configuration

- tests/unit/setup.js
Since `httpRequest` is only used in the browser, it doesn't matter much if we are using `node-fetch`, `isomorphic-fetch`, `undici` or node's native fetch. Said that, to avoid tests to fail on Node 18 (which includes a native fetch implementation), we can overwrite the global fetch with node-fetch's implementation.
> tests: always use node-fetch to simulate browser fetch

- libs/fetcher.client.js
In the server Fetchr, the options passed to the constructor are optional and we then use default values.
That was not the same in the client Fetchr.
> fix: make options optional in fetchr client just as in server

- README.md
- libs/fetcher.client.js
- libs/fetcher.js
- libs/util/httpRequest.js
- tests/util/testCrud.js
Now the request object returned by fetchr crud methods are [thenable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise#thenables) by default. 
To make it possible, I had to refactor `httpRequest` to transform it in a class to make it easier to expose `then`, `catch` and `abort` to the users. By doing it, it was also possible to simplify the `Request` class and remove some workarounds related to `abort`.
This PR also implement some of the stuff we discussed in https://github.com/yahoo/fetchr/pull/263#issuecomment-881089203 without the need for a major version bump. 
```js
// superagent style
fetchr
.read('foo')
.end()
.then()
// callback style without callback
fetchr
.read('foo', null) // passing a second params was necessary to not trigger the …
```
> feat: make Request object thenable

- libs/fetcher.client.js
- libs/fetcher.js
- libs/util/httpRequest.js
- tests/functional/fetchr.test.js
- tests/unit/libs/util/httpRequest.js
I found a bug in our system where we were resolving the request multiple times. The first time it was resolved it was fine (and so fetchr tests), but the second time it would resolve with an undefined value. The code was looking something like this:
```js
const request = fetchr.read('foo', { bar: 42 }); // request was triggered
track(request); // would call then internally
return request; // the consumer of this function would also call then
```
Fixing it was simple, we just had to keep the reference to fetch promise in `httpRequest` and always return …
> fix: always return the same value when resolving requests multiple times

- README.md
- libs/fetcher.js
- tests/functional/resources/alwaysSlow.js
- tests/functional/resources/error.js
- tests/functional/resources/headers.js
- tests/functional/resources/item.js
- tests/functional/resources/slowThenFast.js
- tests/functional/resources/wait.js
- tests/mock/MockErrorService.js
- tests/mock/MockService.js
This PR enables fetchr to be used without any callback.
```js
function create(req, resource, params, body, config, callback) { 
callback(err, data, meta)
}
```
```js
async function create({ req, resource, params, body, config }) {
return { data, meta }
}
```
It's still possible to use the old signature since we detect the new one based on the number or arguments defined in the handler.
This change also make it simple to create handlers that do not require any argument:
```js
function create(req, resource, params, body, config, callback) {
callback({ ok: true …
```
> feat: add support for async based resource operation handlers

- libs/fetcher.js
- tests/functional/app.js
- tests/functional/fetchr.test.js
- tests/unit/libs/fetcher.client.js
- tests/unit/libs/fetcher.js
- tests/util/testCrud.js
We are getting some alerts on our systems whenever some bot our security scanner try to hit a fetchr resource using an operation that is not registered. 
The most common case is when a resource only implements the `create` method (which requires a POST request). The bots try to hit this resource with a GET request, which makes fetchr middleware to think that this is a a `read` operation. Since the resource does not implement it, fetchr throws an error. Before this change this error wouldn't include a status code which would default to a 500. But since this is a client error and we are talking about not implemented methods, I thought that a 405 would be more appropriate.
I really thought that this would be a trivial change (I actually tried it a long time ago, but I gave up and just …
> fix: prevent fetchr to throw a 500 whenever a resource does not implement an operation
